shortUrl:
    path: /shortUrl
    controller: App\Controller\Shortener::shortUrl

index:
    path: /{url}
    controller: App\Controller\Shortener::index
    defaults:
        url: null
    methods: [GET]